### ISSUE TITLE
可以用 npm 引入吗？

### ISSUE THREAD

**Issue by Tymon42** [ddiu8081/blive-message-listener#1]
RT

**Comment by ddiu8081** [comment]
目前还在开发中没有release，开发完成后会支持npm导入

**Comment by Tymon42** [comment]
谢谢大佬

**Comment by Clinale** [comment]
大佬，我在使用node时遇到了一点问题，我的代码如下：
```js
// bili.mjs
import { startListen, MsgHandler } from 'blive-message-listener';
// const blive = require('blive-message-listener')
// 浏 览 器 环 境 ， 从  '/browser' 导 入  startListen
// import { startListen } from 'blive-message-listener/browser'
const handler: MsgHandler = {
  onIncomeDanmu: (msg) => {
    console.log(msg.id, msg.body);
  },
  onIncomeSuperChat: (msg) => {
    console.log(msg.id, msg.body);
  },
};
const instance = startListen(xxx, handler);
instance.close();
```

然后运行`node bili.mjs`，上述代码报错:

> const handler: MsgHandler ={
>       ^^^^^^^
> SyntaxError: Missing initializer in const declaration

我对node不太熟悉，也检索了一些资料，都没有找到解决方案，还请大佬不吝赐教

**Comment by starknt** [comment]
> 大佬，我在使用node时遇到了一点问题，我的代码如下：
> 
> ```js
> // bili.mjs
> import { startListen, MsgHandler } from 'blive-message-listener';
> // const blive = require('blive-message-listener')
> // 浏 览 器 环 境 ， 从  '/browser' 导 入  startListen
> // import { startListen } from 'blive-message-listener/browser'
> const handler: MsgHandler = {
>   onIncomeDanmu: (msg) => {
>     console.log(msg.id, msg.body);
>   },
>   onIncomeSuperChat: (msg) => {
>     console.log(msg.id, msg.body);
>   },
> };
> const instance = startListen(xxx, handler);
> instance.close();
> ```
> 
> 然后运行`node bili.mjs`，上述代码报错:
> 
> > const handler: MsgHandler ={
> > ^^^^^^^
> > SyntaxError: Missing initializer in const declaration
> 
> 我对node不太熟悉，也检索了一些资料，都没有找到解决方案，还请大佬不吝赐教

你使用 `js` 不需要类型标注，你可以尝试搜索 `typescript` 获取更多信息
