### ISSUE TITLE
是否无法支持短房号？

### ISSUE THREAD

**Issue by Nauxscript** [ddiu8081/blive-message-listener#19]
发现有些房间的房间号是比较短的，房号只有 3、4 位（好像是排行榜靠前的或者一些比较火的主播会有这样的房间号），通过这种短的房号无法抓到弹幕；不知道是什么原因呢？有点疑惑；有没有一些解决方法？

**Comment by ddiu8081** [comment]
短房间号需要转为长房间号传进去，可自己调用 api 获取 (#15 )。

有计划把这部分在内部直接处理了，不过浏览器端还会有跨域问题，所以暂时还是自己转一下吧。

**Comment by Nauxscript** [comment]
原来如此，明白了，十分感谢；
还有个小问题，目前没有发现哪里可以获取主播名字，我只在那个 `User` 类型中的 `badge` 信息中看到有个主播名，不过感觉如果从这里获取有点奇怪；是否需要用其他接口来获取呢？或者有其他地方可以获取？

#15 的接口数据中貌似也没有这个数据。

**Comment by ddiu8081** [comment]
> 

看起来这个接口只能获取到主播 uid，需要从其他接口取名字。[SocialSisterYi/bilibili-API-collect](https://github.com/SocialSisterYi/bilibili-API-collect) 仓库有 api 的合集，获取主播名字可用 `/x/space/acc/info`

**Comment by Nauxscript** [comment]
好的，十分感谢！
