### ISSUE TITLE
[FEATURE] 完善更多常用事件

### ISSUE THREAD

**Issue by pkptzx** [ddiu8081/blive-message-listener#22]
还有这几个事件你都加上呗 ^_^  我常用
- 点赞的人 LIKE_INFO_V3_CLICK 
- 房管这俩可以定义到一起:
    - 设立房管 room_admin_entrance
    - 撤销房管 ROOM_ADMIN_REVOKE
- 发送红包POPULARITY_RED_POCKET_NEW

更多信息请参考:
https://github.com/SocialSisterYi/bilibili-API-collect/issues/360

**Comment by ddiu8081** [comment]
v0.4.3 先做了点赞和房管，点赞合并到 `onUserAction` 里了；

红包等我自己抓下消息再看

**Comment by ddiu8081** [comment]
v0.4.4 补上了红包抽奖和天选时刻抽奖事件
