### ISSUE TITLE
调用close方法时，会触发两次onClose

### ISSUE THREAD

**Issue by yige233** [ddiu8081/blive-message-listener#24]
### Describe the bug

代码如下：
```
import { startListen } from "blive-message-listener";

const listener = startListen(652581, {
  onClose: () => console.log("与直播间的连接断开了"),
});

setTimeout(() => listener.close(), 2000);

```

console.log会被执行两次：
```
与直播间的连接断开了
与直播间的连接断开了
```

感觉像是tiny-bilibili-ws的问题，但不确定到底是什么原因

### Reproduction

none

### System Info

```Shell
node v16.13.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by starknt** [comment]
确实是`tiny-bilibili-ws` 的问题， 应该会在 `v0.1.7` 修复(o^^o)
