### ISSUE TITLE
为保护用户隐私，未登录无法查看他人昵称

### ISSUE THREAD

**Issue by yaoyaochil** [ddiu8081/blive-message-listener#29]
### Additional context

现在b站不登录的情况下不允许查看相关内容了，是不是可以新增一个配置项 传入cookie等信息 或者header自定义配置

**Comment by ddiu8081** [comment]
目前是可以传第三个参数配置 auth 参数的：
```ts
startListen(652581, handler, {
  ws: {
    uid: 1,
    platform: undefined,
  }
})
```

经过测试目前发现了两种办法可以展示完整的：
1. uid 传有效 uid，同时 platform 传非 `web` 值或者 `undefined`
2. uid, key, buvid 传登录后抓取的真实数据

**Comment by starknt** [comment]
后续我会重写一下，接入新的认证机制
