### ISSUE TITLE
Large amount of danmu freshes when the liver draws a lottery

### ISSUE THREAD

**Issue by widcardw** [ddiu8081/blive-message-listener#6]
当某位 UP 发起一次天选之人时，会有大量的抽奖弹幕，在一定程度上会挤掉文字性弹幕。此处我使用了白河愁的直播间（老白真的好喜欢抽奖）。

改进方案：可以通过弹幕消息中的 `data.info[0][9]` 字段初步判断是不是抽奖弹幕，当这个字段不是 0，则可能是抽奖弹幕，在 [我的分析](https://github.com/widcardw/D4nm4ku/blob/e71d34b43972a286cd89b82f81ceaea1874bbe21/src/composables/types.ts#L34) 中给出了初步的判断

<img width="905" alt="image" src="https://user-images.githubusercontent.com/55699713/192139989-b616058e-8789-4a47-acc9-a79891102690.png">

上图中颜文字弹幕就是抽奖弹幕

**Comment by ddiu8081** [comment]
感谢，我研究下加个字段
