### ISSUE TITLE
关于关闭 TCP 连接

### ISSUE THREAD

**Issue by Tymon42** [ddiu8081/blive-message-listener#8]
https://github.com/ddiu8081/blive-message-listener/blob/7db1bd4f143875761e38f2139309b87f8948f3b2/src/index.ts#L6

如果需要断开 TCP/WS 连接，[simon300000/bilibili-live-ws](https://github.com/simon300000/bilibili-live-ws) 提供了 `live.close()` 方法。  
但是本项目中 `live` 并没有返回，是否有可能把 `live` 一并作为 `startListen()` 的返回值，以方便关闭连接？

**Comment by ddiu8081** [comment]
v0.1.13 新增导出了 `MessageListener` 实例，包含`close` 在内的一些方法
